export const items = [
  {
    id: "p1",
    category: "chair",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F1.jpg?alt=media&token=f243a15a-42df-44d1-9546-dee0277c7bb1",
    description: "Little Armchair Sheepskin",
    price: 986,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fother1.jpg?alt=media&token=b059c186-bcc7-46db-b9e6-27a103a0a8ed",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fother2.jpg?alt=media&token=fa5dd1c5-2559-4070-b5c6-267d2476fea2",
    ],
    specs:
      "Tradition Little Petra VB1 Armchair Sheepskin Moonlight/ Walnut/ Brass Limited Edition | We give you a special discount when you put this product in the basket.",
    texture: "Sheep Skin",
    weight: "15kg",
    size: "150cm x 70cm",
    star: true,
    trend: false,
  },
  {
    id: "p2",
    category: "kitchen",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F2.jpg?alt=media&token=ad76ad6b-1949-4ad4-95e4-ad08a606cb2d",
    description: "Pop-Up Toaster",
    price: 45,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Ftoster1.jpg?alt=media&token=a2ba8614-5d66-460c-a620-b4b180d0fd77",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Ftoster2.jpg?alt=media&token=87e1ab49-d3de-4941-8060-a477a0870dc3",
    ],
    specs:
      " The rounded square design of the toaster allows it to fit neatly against a wall, or inside a corner. Excellent at defrosting, and with the perfect breadtoheater distance to give crunchy toast with a soft, spongey middle.",
    texture: "Plastic",
    weight: "3.5kg",
    size: "20xm x 10cm",
    star: true,
    trend: false,
  },
  {
    id: "p3",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F3.png?alt=media&token=716360e3-56a6-4a7d-a696-8d91577c8144",
    description: "Lamp Light Blue",
    price: 79,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Flampblue1.webp?alt=media&token=db47409e-b86b-4121-aac3-3b637085de28",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Flampblue2.webp?alt=media&token=b1087952-1b88-4906-bdee-5ae43e1bafd3",
    ],
    specs:
      "The Verner Panton Flowerpot , designed in 1968, was originally intended for the restaurant industry and Verner Panton exhibitions.",
    texture: "Plastic",
    weight: "2kg",
    size: "15cm x 15cm",
    star: true,
    trend: false,
  },
  {
    id: "p4",
    category: "furniture",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F4.jpg?alt=media&token=4f3c2da0-a283-4166-b232-72199de987a7",
    description: "Pulp Unit - 5 Compartments",
    price: 254,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fpulpunit1.jpg?alt=media&token=ad838e18-b57f-427d-8681-25147bbd8e81",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fpulpunit2.jpg?alt=media&token=7fcbe239-b764-45ff-a906-1202e77936f8",
    ],
    specs:
      "Pulp Units are lightweight and durable, and can be used horizontally or vertically. Designed with A4 paper in mind, MUJI angle files and ring binders fit neatly inside.",
    texture: "Wood",
    weight: "45kg",
    size: "250cm x 60cm",
    star: true,
    trend: false,
  },
  {
    id: "p5",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F5.jpg?alt=media&token=80ba2ccf-b92f-458e-b477-04a5d3a31871",
    description: "Golden Modern Light",
    price: 189,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fmoderngold1.webp?alt=media&token=321adf7e-0092-4322-a59f-f54e295c2bfa",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fmoderngold2.webp?alt=media&token=3f9a6aa4-5073-49e7-91bb-ffda4c72d745",
    ],
    specs:
      "Tom Dixon and FRONT have created an incredibly beautiful pendant, in a completely unique design. The lamp is made using a special metallization technology that makes the look completely unique. The first of its kind. the lamp is transparent when its on and you can see the exciting play of colors.",
    texture: "Plastic",
    weight: "3kg",
    size: "20cm x 20cm",
    star: true,
    trend: false,
  },
  {
    id: "p6",
    category: "skincare",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F6.jpg?alt=media&token=022edd28-21a1-4e64-9978-422f1d61258a",
    description: "Body Oil 200ml",
    price: 67,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcleaningoil1.jpg?alt=media&token=07c566cb-3618-463a-b9ed-4f5f888d1550",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcleaningoil2.jpg?alt=media&token=103c47c7-ca90-4e12-a840-9805bf7a9479",
    ],
    specs:
      "Made from 100% plant-based oils with olive oil as the main ingredient, this cleansing oil is gentle on the skin. Free from fragrance, colours and, mineral oils, paraben free, alcohol free, allergy tested (we cannot guarantee that it will not cause allergies in any users) * How to use: Take a small amount in the palm of your hand, and massage into the face to remove make-up and dirt. Rinse well with cold or warm water",
    texture: "Liquid",
    weight: "200ml",
    size: "10cm x 5cm",
    star: true,
    trend: false,
  },
  {
    id: "p7",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F7.jpg?alt=media&token=402f54f7-89c4-4b2f-b34e-395d17fcc03d",
    description: "Black and White Lamp",
    price: 220,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fblackandwhite1.webp?alt=media&token=bc363a6d-e6b0-4bb8-893a-084d00b34e10",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fblackandwhite2.webp?alt=media&token=242f155e-0821-430a-8925-cb3c136c0afc",
    ],
    specs:
      "Concept: Dot is inspired by perforated metal and the patterns that light creates when it shines through the small holes. The contrast between the coarse perforated metal and the smooth opal glass makes the Dot a simple and meaningful pendant. With its elegant expression, Shine, whether the light is on or off.",
    texture: "Plastic",
    weight: "6kg",
    size: "20cm x 20cm",
    star: true,
    trend: false,
  },
  {
    id: "p8",
    category: "furniture",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F8.jpg?alt=media&token=64389535-bbbf-4ba7-a8c0-afc7f7f8d8fe",
    description: "Gejst Shelf A Black Ash/Black",
    price: 115,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fshelf1.webp?alt=media&token=87645950-29f4-476c-b8aa-8c0183705ed6",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fshelf2.webp?alt=media&token=f0885e7b-3937-4673-b3ce-822d97ae47d7",
    ],
    specs:
      "Designed by Böttcher & Kayser, Nivo is a minimalist wall shelf designed with functionality and aesthetics in mind. Without unnecessary details and clean lines, this collection hangs easily and elegantly on the wall, creating calm and an overview of the things you want to put on the shelf.",
    texture: "Wood",
    weight: "10kg",
    size: "60cm x 20cm",
    star: true,
    trend: false,
  },
  {
    id: "p9",
    category: "furniture",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F9.png?alt=media&token=023da926-f799-4b55-9543-95fc5379e511",
    description: "Cube Lolo Vase Black",
    price: 161,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fvase1.webp?alt=media&token=be73d3a2-3b18-4db7-9fa1-f1cd4221e2f1",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fvase2.webp?alt=media&token=8c405037-f3de-4212-a8b2-bd15eb8b0fa5",
    ],
    specs:
      "Kubus Vase Lolo was originally designed by Søren Lassen in 2014, but was launched in connection with by Lassens 10 year anniversary 2018. The vase is a natural and sought-after extension of the series, which already counts the Kubus candlesticks and Kubus Bowl Bowl. Set it alone or in a still life, fill it with airy, colorful flowers for a feminine look or leave it alone in all its simplicity and precision.",
    texture: "Ceramics",
    weight: "12kg",
    size: "45cm x 15cm",
    star: false,
    trend: true,
  },
  {
    id: "p10",
    category: "chair",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F10.jpg?alt=media&token=41c95d3b-4264-43bf-ace4-918897c1d878",
    description: "Traditional Armchair",
    price: 89,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fchairboom1.webp?alt=media&token=7048fbc5-e27a-415b-a4ab-b419665fd07c",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fchairboom2.webp?alt=media&token=3c20b6e7-242c-4155-90ab-ae08bf5aa89e",
    ],
    specs:
      "Concept: &Tradition's Boomerang lounge chair is a classic Danish design with a modern and minimalist expression. The chair was designed by Hvidt & Mølgaard in 1956, and with its stylish cushions and hand-polished wooden frame, it is an ideal Nordic design that gives a personal mark to the home.",
    texture: "Wood",
    weight: "8kg",
    size: "60cm x 40cm",
    star: false,
    trend: true,
  },
  {
    id: "p11",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F11.jpg?alt=media&token=3138dc3e-ec4e-4299-b468-119a4ebc817c",
    description: "The Sun Pendant Black",
    price: 160,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fblacklamp1.webp?alt=media&token=b6315914-f849-4e29-bf16-32fcbb962089",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fblacklamp2.jpg?alt=media&token=6ed88293-77ea-4f98-88b5-9279dd69cb8a",
    ],
    specs:
      "The Here Comes The Sun pendant designed by Bertrand Balas is a quality lamp with a unique and magical look. The Here Comes The Sun series has a fantastic expression and especially swhen turned on it creates a very special atmosphere in the room it hangs in. The lamp fits perfectly above both dining room table, kitchen counter, and as living room lighting . ",
    texture: "Plastic",
    weight: "4kg",
    size: "20cm x 20cm",
    star: false,
    trend: true,
  },
  {
    id: "p12",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F12.png?alt=media&token=202c520a-3a16-4486-b097-b0bc6ea97e6c",
    description: "Simple Golden Lamp",
    price: 220,
    otherImgs: [
      "https://console.firebase.google.com/project/e-commerce-bed4b/storage/e-commerce-bed4b.appspot.com/files/~2Fproducts~2FotherProducts",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fgoldenlamp2.webp?alt=media&token=abe454f4-5bd1-485a-a783-4f004dc231a1",
    ],
    specs:
      "Verner Panton Flowerpot, designed in 1968, was originally meant for the hospitality industry and Verner Panton displays and showrooms. The lamp then became popular in private homes, and due to its stylish design and many colour choices, it has made a major comeback in recent years.",
    texture: "Plastic",
    weight: "4kg",
    size: "15cm x 15cm",
    star: false,
    trend: true,
  },
  {
    id: "p13",
    category: "skincare",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F13.jpg?alt=media&token=090c7ce7-417a-42f6-bbd3-1fb378713421",
    description: "Unbleached Cotton Pads 180",
    price: 33,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcotton1.jpg?alt=media&token=7e09a563-01fd-472e-abd9-0ed8d4c91f2d",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcotton2.jpg?alt=media&token=030a0d73-85bc-4281-9900-4f4798e5bbf6",
    ],
    specs:
      "Cotton pads made from soft, unbleached cotton. These are made in Japan and made from 100% cotton.",
    texture: "Cotton",
    weight: "180g",
    size: "20cm x 10cm",
    star: false,
    trend: true,
  },
  {
    id: "p14",
    category: "chair",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F14.png?alt=media&token=28b843ce-64a2-412a-9126-837d53263c2b",
    description: "Oak Spanish Chair",
    price: 520,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fwoodchair1.webp?alt=media&token=9575d0fb-231a-4aed-af9d-3f0baa6824ef",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fwoodchair2.webp?alt=media&token=c77b0208-7a8a-4142-acb2-56bb49c46bda",
    ],
    specs:
      "When talking about Børge Mogensen, The Spanish Chair is probably one of the first designs you would think of, which makes good sense as it is also one of his most recognized products around the world.",
    texture: "Wood",
    weight: "15kg",
    size: "60cm x 30cm",
    star: false,
    trend: true,
  },
  {
    id: "p15",
    category: "chair",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F15.jpg?alt=media&token=f7a9ef2a-748b-44e3-a0aa-7d4a1253c770",
    description: "Copenhagen Armchair",
    price: 330,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcopenhagen1.webp?alt=media&token=a6bd2914-cc5f-43d0-b484-3d1a1fca3739",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcopenhagen2.webp?alt=media&token=43e7f7b4-df63-4352-8b85-5c33afd0b828",
    ],
    specs:
      "Concept: The Hyg series by Danish Normann Copenhagen is a series of chairs based on the Danish word Hygge. The designer Simon Legald has tried to embody the meaning of the word around security, warmth and convenience in a furniture series. This is expression in the fine organic shapes and hearty curves that provide a high degree of sitting comfort and well-being in the chairs. ",
    texture: "Wood",
    weight: "14kg",
    size: "65cm x 35cm",
    star: false,
    trend: true,
  },
  {
    id: "p16",
    category: "electronic",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F16.jpg?alt=media&token=94b7d57b-4a52-411e-8101-748ddf618672",
    description: "Anti Dark Light",
    price: 120,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcam1.webp?alt=media&token=093c8740-ad54-49ba-9e28-31e4fe56c219",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcam2.jpg?alt=media&token=e2d4bb2c-cb62-49e0-ab4a-0d661bca50e6",
    ],
    specs:
      "Easy Mini W75 from Antidark lives fully up to its name. Simple design, comfortable light, easy to adjust. The Easy Wall Light has made it easy for the user to handle, well, everything! The Easy lamp can turn 360 degrees and be tipped. An ideal lamp that can be placed in connection with other lamps to achieve light in all corners of the room. Furthermore, the lamp can work as a wall light or ceiling",
    texture: "Metal",
    weight: "2kg",
    size: "15cm x 10cm",
    star: false,
    trend: true,
  },
  {
    id: "p17",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F17.png?alt=media&token=405918bf-2a61-4a3f-ad58-1a6615d82c60",
    description: "Table Lamp",
    price: 75,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Ftablelamp1.webp?alt=media&token=7e968b86-7e0f-4614-adc2-39ccc5dd1339",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Ftablelamp2.webp?alt=media&token=3a6b6cd6-8bab-4822-8198-769fa67cf8e8",
    ],
    specs:
      "The lamp has also become popular in private homes and has especially made a comeback in recent years. This is not least due to the lamp's stylish design and the many color options that make it fit everywhere.",
    texture: "Metal",
    weight: "5kg",
    size: "25cm x 15cm",
    star: false,
    trend: true,
  },
  {
    id: "p18",
    category: "lamp",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F18.png?alt=media&token=f4626318-6d52-4e58-bb92-d172755755ce",
    description: "Mat Black Lamp",
    price: 175,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fmat1.webp?alt=media&token=28258eaf-6206-4cc8-97a0-44799effd7de",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fmat2.webp?alt=media&token=3c94cef7-b769-4beb-815d-dfb48c209004",
    ],
    specs:
      "Unique offer We give you a special discount when you put this product in the basket. *Only applies to specific products.",
    texture: "Metal",
    weight: "6kg",
    size: "20cm x 15cm",
    star: false,
    trend: true,
  },
  {
    id: "p19",
    category: "chair",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F19.jpg?alt=media&token=d63a8242-c2a0-4f07-82d8-96ac2677a71b",
    description: "Comfy Chair",
    price: 119,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcomfy1.webp?alt=media&token=1cce237e-bf34-4561-a999-0a9f07c9f1b9",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fcomfy2.webp?alt=media&token=6dd4c566-5d43-4188-9550-35a45c2f9ea8",
    ],
    specs:
      "Sum is a series designed by the Danish designer Simon Legald, who is the epitome of modern elegance. Elegant and resolute as the tip of a wing, the armrests spread out invitingly, as if they want to embrace you in the armchair's soft, homely space.",
    texture: "Comfy Material",
    weight: "25kg",
    size: "60cm x 30cm",
    star: false,
    trend: true,
  },
  {
    id: "p20",
    category: "skincare",
    img: "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2F20r.jpg?alt=media&token=991ca615-ee78-4adb-af5b-dea1e7568a9c",
    description: "Body Oil 50ml",
    price: 45,
    otherImgs: [
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fbodyoil1.jpg?alt=media&token=f07ae095-e0f4-435d-9402-711deef5e9f8",
      "https://firebasestorage.googleapis.com/v0/b/e-commerce-bed4b.appspot.com/o/products%2FotherProducts%2Fbodyoil2.jpg?alt=media&token=17bdf92c-548e-49f3-8de4-5035e0423c64",
    ],
    specs:
      "Made from 100% plant-based oils with olive oil as the main ingredient, this cleansing oil is gentle on the skin. Free from fragrance, colours and, mineral oils, paraben free, alcohol free, allergy tested (we cannot guarantee that it will not cause allergies in any users) * How to use: Take a small amount in the palm of your hand, and massage into the face to remove make-up and dirt. Rinse well with cold or warm water.",
    texture: "Liquid",
    weight: "50ml",
    size: "10cm x 5cm",
    star: false,
    trend: true,
  },
];
